services:
  redis:
    ports:
      - "63790:6379"

  backend:
    user: "0:0"
    command:
      [
        "python",
        "-m",
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8010",
        "--reload",
      ]
    volumes:
      - .:/app

  frontend:
    user: "0:0"
    command: ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3100"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
